export { MainPage } from './MainPage/MainPage'
export { GlobalPage } from './GlobalPage/GlobalPage'
export { BookCatalogPage } from './BookCatalogPage/BookCatalogPage'
export { ServiceRulesPage } from './ServiceRulesPage/ServiceRulesPage'
export { ExchangeAndDeliveryPage } from './ExchangeAndDeliveryPage/ExchangeAndDeliveryPage'
export { ReviewsPage } from './ReviewsPage/ReviewsPage'
export { AuthPage } from './AuthPage/AuthPage'